/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.helpmobile.forms;

/**
 *
 * @author Tanman
 */
public enum Country {
    AFGHANISTAN("Afghanistan"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    AMERICANSAMOA("American Samoa"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANGUILLA("Anguilla"),
    ANTARCTICA("Antarctica"),
    ANTIGUA("Antigua"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    ARUBA("Aruba"),
    ASCENSIONISLAND("Ascension Island"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BAHAMAS("Bahamas"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BARBUDA("Barbuda"),
    BELARUS("Belarus"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BERMUDA("Bermuda"),
    BHUTAN("Bhutan"),
    BOLIVIA("Bolivia"),
    BOSNIAANDHERZEGOWINA("Bosnia and Herzegowina"),
    BOTSWANA("Botswana"),
    BRAZIL("Brazil"),
    BRITISHVIRGINISLANDS("British Virgin Islands"),
    BRUNEIDARUSSALAM("Brunei Darussalam"),
    BULGARIA("Bulgaria"),
    BURKINAFASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODIA("Cambodia"),
    CAMEROON("Cameroon"),
    CANADA("Canada"),
    CAPEVERDEISLANDS("Cape Verde Islands"),
    CAYMANISLANDS("Cayman Islands"),
    CENTRALAFRICANREPUBLIC("Central African Republic"),
    CHAD("Chad"),
    CHATHAMISLAND("Chatham Island"),
    CHILE("Chile"),
    CHINA("China"),
    CHRISTMASISLAND("Christmas Island"),
    COCOSKEELINGISLANDS("Cocos-Keeling Islands"),
    COLOMBIA("Colombia"),
    COMOROS("Comoros"),
    CONGO("Congo"),
    COOKISLANDS("Cook Islands"),
    COSTARICA("Costa Rica"),
    CUBA("Cuba"),
    CROATIA("Croatia"),
    CURACAO("Curacao"),
    CYPRUS("Cyprus"),
    CZECHREPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    DIEGOGARCIA("Diego Garcia"),
    DOMINICA("Dominica"),
    DOMINICANREPUBLIC("Dominican Republic"),
    DJIBOUTI("D'Jibouti"),
    EASTERISLAND("Easter Island"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    ELSALVADOR("El Salvador"),
    EQUATORIALGUINEA("Equatorial Guinea"),
    ERITREA("Eritrea"),
    ESTONIA("Estonia"),
    ETHIOPIA("Ethiopia"),
    FAROEISLANDS("Faroe Islands"),
    FALKLANDISLANDS("Falkland Islands"),
    FIJIISLANDS("Fiji Islands"),
    FINLAND("Finland"),
    FRANCE("France"),
    FRENCHANTILLES("French Antilles"),
    FRENCHGIUANA("French Giuana"),
    FRENCHPOLYNESIA("French Polynesia"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GERMANY("Germany"),
    GHANA("Ghana"),
    GIBRALTAR("Gibraltar"),
    GREECE("Greece"),
    GREENLAND("Greenland"),
    GRENADA("Grenada"),
    GRENADINEISLANDS("Grenadine Islands"),
    GUADALUPE("Guadalupe"),
    GUAM("Guam"),
    GUANTANAMOBAYCUBA("Guantanamo Bay (Cuba)"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    GUINEABISSAU("Guinea-Bissau"),
    GUYANA("Guyana"),
    HAITI("Haiti"),
    HONDURAS("Honduras"),
    HONGKONG("Hong Kong"),
    HUNGARY("Hungary"),
    ICELAND("Iceland"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAN("Iran"),
    IRAQ("Iraq"),
    IRELAND("Ireland"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    IVORYCOAST("Ivory Coast"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    JORDAN("Jordan"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRIBATI("Kiribati"),
    KOREAREPUBLICOF("Korea (Republic of)"),
    KUWAIT("Kuwait"),
    KYRGYZREPUBLIC("Kyrgyz Republic"),
    LAOS("Laos"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LESOTHO("Lesotho"),
    LIBERIA("Liberia"),
    LIBYA("Libya"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MACAU("Macau"),
    MACEDONIA("Macedonia"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTA("Malta"),
    MARSHALLISLANDS("Marshall Islands"),
    MARTINIQUE("Martinique"),
    MAURITANIA("Mauritania"),
    MAURITUS("Mauritus"),
    MAYOTTEISLAND("Mayotte Island"),
    MEXICO("Mexico"),
    MICRONESIA("Micronesia"),
    MIDWAYISLAND("Midway Island"),
    MOLDOVAREPUBLICOF("Moldova (Republic of)"),
    MONACO("Monaco"),
    MONGOLIA("Mongolia"),
    MONTSERAT("Montserat"),
    MOROCCO("Morocco"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NETHERLANDSANTILLES("Netherlands Antilles"),
    NEVIS("Nevis"),
    NEWCALEDONIA("New Caledonia"),
    NEWZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NIUE("Niue"),
    NORFOLKISLAND("Norfolk Island"),
    NORTHERNMARIANASISLANDS("Northern Marianas Islands"),
    NORWAY("Norway"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PALAU("Palau"),
    PALESTINE("Palestine"),
    PANAMA("Panama"),
    PAPUANEWGUINEA("Papua New Guinea"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    PUERTORICO("Puerto Rico"),
    QATAR("Qatar"),
    RÉUNIONISLAND("Réunion Island"),
    ROMANIA("Romania"),
    RUSSIANFEDERATION("Russian Federation"),
    RWANDA("Rwanda"),
    SANMARINO("San Marino"),
    SAOTOMEANDPRINCIPE("Sao Tome and Principe"),
    SAUDIARABIA("Saudi Arabia"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRALEONE("Sierra Leone"),
    SINGAPORE("Singapore"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOLOMONISLANDS("Solomon Islands"),
    SOMALIA("Somalia"),
    SOUTHAFRICA("South Africa"),
    SPAIN("Spain"),
    SRILANKA("Sri Lanka"),
    STHELENA("St. Helena"),
    STKITTS("St. Kitts"),
    STLUCIA("St. Lucia"),
    STPIERREETMIQUELON("St. Pierre et Miquelon"),
    SUDAN("Sudan"),
    SURINAME("Suriname"),
    SWAZILAND("Swaziland"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    SYRIA("Syria"),
    TAHITI("Tahiti"),
    TAIWAN("Taiwan"),
    TAJIKISTAN("Tajikistan"),
    TANZANIA("Tanzania"),
    THAILAND("Thailand"),
    TIMORLESTE("Timor-Leste"),
    TOGO("Togo"),
    TOKELAUISLANDS("Tokelau Islands"),
    TONGAISLANDS("Tonga Islands"),
    TRINIDADANDTOBAGO("Trinidad and Tobago"),
    TUNISIA("Tunisia"),
    TURKEY("Turkey"),
    TURKMENISTAN("Turkmenistan"),
    TURKSANDCAICOSISLANDS("Turks and Caicos Islands"),
    TUVALU("Tuvalu"),
    UGANDA("Uganda"),
    UKRAINE("Ukraine"),
    UNITEDARABEMIRATES("United Arab Emirates"),
    UNITEDKINGDOM("United Kingdom"),
    UNITEDSTATES("United States"),
    URUGUAY("Uruguay"),
    USVIRGINISLANDS("US Virgin Islands"),
    UZBEKISTAN("Uzbekistan"),
    VANUATU("Vanuatu"),
    VATICANCITY("Vatican City"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    WAKEISLAND("Wake Island"),
    WALLISANDFUTUNAISLANDS("Wallis and Futuna Islands"),
    WESTERNSAMOA("Western Samoa"),
    YEMENARABREPUBLIC("Yemen-Arab Republic"),
    ZAMBIA("Zambia"),
    ZANZIBAR("Zanzibar"),
    ZIMBABWE("Zimbabwe");

    private final String label;

    private Country(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
